#' Intraclass Correlation Coefficient (ICC) for a set of athlete measurements
#'
#' Computes the ICC for each vector of measurements that is passed to the function, for the vectors that are the first two arguments
#'   called to the function (the subject vector and the trial vector, in that order)
#'
#' @param subject The vector of athletes who recorded the results for each metric (can be a numeric or factor variable)
#' @param trial The vector that represents which trial each measurement came from
#' @param ... Numeric vectors that represent the metrics for which the ICC should be computed. These vectors hold the scores that
#'   each athlete recorded for each respective metric (at least one metric must be passed to the function)
#' @return A list, with its contents being the ICC output (generated by the ICC from the psych package, with the statistics for the six
#'   types of ICC's), is returned when this function is called
#' @example
#' subject <- c(1, 1, 1, 2, 2, 2, 3, 3, 3)
#' trial <- c('Trial 1', 'Trial 2', 'Trial 3', 'Trial 1', 'Trial 2', 'Trial 3', 'Trial 1', 'Trial 2', 'Trial 3')
#' metric_1 <- c(257, 268, 237, 275, 259, 263, 216, 287, 250)
#' metric_2 <- c(1.11, 1.24, 0.89, 1.37, 1.21, 1.30, 0.75, 1.42, 1.15)
#' ICC(subject, trial, metric_1, metric_2)

#' @export
ICC <- function(subject, trial, ...) {

  #The inputs to this function are individual vectors, so here they are brought together into one data frame
  ICC_df_full <- data.frame(subject, trial, ...)

  #This for loop iterates over the arguments passed to the function that represent the measurements for the various metrics
  for (i in 3:nargs()) {

    #For each loop, we want to make a new dataset (data1) with only three columns: Subject, Trial, and the ith metric in the for loop
    ICC_df_part <- ICC_df_full[, c(1, 2, i)]

    #Converts the data frame to the wide format needed to use the ICC function from the psych package later on
    ICC_df_part <- pivot_wider(ICC_df_part, names_from = trial, values_from = colnames(ICC_df_full)[i])

    #The vector of subjects (the first column) cannot be part of the data frame in order to use the ICC function from the psych package
    ICC_df_part <- ICC_df_part[, -1]

    #Computes the ICC for the given metric (the psych:: must be included in order to differentiate from our ICC function)
    ICC = psych::ICC(ICC_df_part)

    #Put the results of the above code into a list, which allows us to see the ICC output for all of the metrics in our function's output
    list_ICC <- list(ICC)

    #Names each item of the list properly, as the ICC Output of its respective metric
    names(list_ICC) <- paste("ICC Output", colnames(ICC_df_full)[i], sep = "--")

    #We must specifically print the list in order to see all of its contents when making it inside of a for loop as we have done here
    print(list_ICC)

  }

}
