#' @title Intraclass Correlation Coefficient (ICC) for a set of athlete measurements
#'
#' @description Computes the ICC for each vector of measurements that is passed to the function, for the vectors that are the first
#'   two arguments called to the function (the subject vector and the trial vector, in that order).
#'
#' @param subject The vector of athletes who recorded the results for each metric
#' @param trial The vector that represents which trial each measurement came from. In order for the function to work, each athlete
#'   must have completed the same number of trials for each metric.
#' @param ... Numeric vectors that represent the metrics for which the ICC output should be given. These vectors hold the scores that
#'   each athlete recorded for each respective metric (at least one metric must be passed to the function).
#'
#' @return A list, with its contents being the ICC output (generated by the ICC from the psych package, with the statistics for the
#'   six types of ICC's), is returned
#'
#' @example
#' subject <- c(1, 1, 1, 2, 2, 2, 3, 3, 3)
#' trial <- c('Trial 1', 'Trial 2', 'Trial 3', 'Trial 1', 'Trial 2', 'Trial 3', 'Trial 1', 'Trial 2', 'Trial 3')
#' metric_1 <- c(257, 268, 237, 275, 259, 263, 216, 287, 250)
#' metric_2 <- c(1.11, 1.24, 0.89, 1.37, 1.21, 1.30, 0.75, 1.42, 1.15)
#' metric_3 <- c(1272, 1493, 1072, 1046, 1198, 1165, 1478, 1370, 1335)
#' ICC(subject, trial, metric_1, metric_2, metric_3)
#'
#' @references Shrout, P. E., &amp; Fleiss, J. L. (1979). Intraclass correlations: Uses in assessing rater reliability. Psychological
#'   Bulletin, 86(2), 420-428.
#'
#' @export
ICC <- function(subject, trial, ...) {

  #The inputs to this function are individual vectors, so here they are brought together into one data frame
  full_df <- data.frame(subject, trial, ...)

  #This for loop iterates over the arguments passed to the function that represent the measurements for the various metrics
  for (i in 3:nargs()) {

    #For each loop, we want to make a new dataset (data1) with only three columns: Subject, Trial, and the ith metric in the for loop
    part_df <- full_df[, c(1, 2, i)]

    #Converts the data frame to the wide format needed to use the ICC function from the psych package later on
    part_df <- tidyr::pivot_wider(part_df, names_from = trial, values_from = colnames(full_df)[i])

    #The vector of subjects must not be part of the data frame in order to use the ICC function from the psych package
    part_df <- part_df[, -1]

    #Computes the ICC for the given metric
    ICC = psych::ICC(part_df)

    #Names each item of the list properly, as the ICC Output of its respective metric
    names(list_ICC) <- colnames(full_df)[i]

    #We must specifically print the list in order to see all of its contents when making it inside of a for loop as we have done here
    print(list_ICC)

  }

}
